defmodule Core.Storage.AudioFile do
  @moduledoc """
  An uploaded audio file.

  Separate from the clip that plays it: one file backs many clips, and its
  lifecycle is its own — uploaded, then analysed, then usable. `status` says
  which of those it has reached, so the UI can show a placeholder waveform
  instead of pretending the file is ready.
  """

  use Ecto.Schema

  import Ecto.Changeset

  @statuses [:pending, :ready, :failed]

  schema "audio_files" do
    field :storage_key, :string
    field :original_filename, :string
    field :content_type, :string
    field :byte_size, :integer
    field :checksum, :string

    field :duration_ms, :integer
    field :peaks, :binary

    field :status, Ecto.Enum, values: @statuses, default: :pending

    belongs_to :project, Core.Projects.Project
    belongs_to :uploaded_by, Core.Accounts.User

    timestamps()
  end

  def statuses, do: @statuses

  @doc """
  Changeset for the record created when an upload is announced.

  `storage_key` is cast rather than taken from the caller's filename: it is
  generated by `Core.Storage.build_key/2`, and the original name is kept in a
  field of its own, for display only.
  """
  def changeset(audio_file, attrs) do
    audio_file
    |> cast(attrs, [
      :project_id,
      :uploaded_by_id,
      :storage_key,
      :original_filename,
      :content_type,
      :byte_size,
      :checksum
    ])
    |> validate_required([
      :project_id,
      :storage_key,
      :original_filename,
      :content_type,
      :byte_size
    ])
    |> validate_number(:byte_size, greater_than: 0)
    |> unique_constraint(:storage_key)
    |> unique_constraint([:project_id, :checksum])
    |> foreign_key_constraint(:project_id)
  end

  @doc "Marks the file usable, with whatever the analysis found."
  def analysed_changeset(audio_file, attrs) do
    audio_file
    |> cast(attrs, [:duration_ms, :peaks, :status])
    |> validate_required([:status])
    |> validate_number(:duration_ms, greater_than: 0)
  end
end
