defmodule Core.Storage.Local do
  @moduledoc """
  Stores files on the local filesystem. Used in dev and test.

  Uploads do not go through the application: the client is handed a `PUT`
  endpoint and sends the bytes there, exactly as it would send them to a
  presigned S3 URL. Keeping the two shapes identical is what lets the same
  tests run against both adapters.

  Files are never served straight off disk with `Plug.Static`: reading one goes
  through the same access check as the project it belongs to, so serving is the
  web layer's job and this module only says where the file lives.
  """

  @behaviour Core.Storage.Adapter

  alias Core.Storage

  # sobelow_skip ["Traversal.FileModule"]
  # The path is not user input by the time it reaches the filesystem:
  # `absolute_path/1` refuses anything that does not resolve inside the root,
  # and the key itself is generated by `Core.Storage.build_key/2`.
  @impl true
  def put(key, data, _opts \\ []) do
    with {:ok, path} <- absolute_path(key),
         :ok <- File.mkdir_p(Path.dirname(path)),
         :ok <- write(path, data) do
      {:ok, key}
    end
  end

  @impl true
  def get_url(key, _opts \\ []), do: {:ok, Path.join(public_prefix(), key)}

  @impl true
  def upload_url(_key, opts \\ []) do
    case Keyword.fetch(opts, :upload_path) do
      {:ok, path} ->
        {:ok,
         %{
           method: "PUT",
           url: path,
           headers: content_type_header(opts),
           expires_at: DateTime.add(DateTime.utc_now(), Storage.upload_url_ttl_seconds(), :second)
         }}

      :error ->
        {:error, :upload_path_required}
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  # The path is not user input by the time it reaches the filesystem:
  # `absolute_path/1` refuses anything that does not resolve inside the root,
  # and the key itself is generated by `Core.Storage.build_key/2`.
  @impl true
  def read(key, opts \\ []) do
    with {:ok, path} <- absolute_path(key) do
      case Keyword.get(opts, :length) do
        nil -> File.read(path)
        length -> read_prefix(path, length)
      end
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  @impl true
  def delete(key) do
    with {:ok, path} <- absolute_path(key) do
      case File.rm(path) do
        :ok -> :ok
        {:error, :enoent} -> :ok
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @impl true
  def stat(key) do
    with {:ok, path} <- absolute_path(key),
         {:ok, %File.Stat{size: size}} <- File.stat(path) do
      {:ok, %{size: size, content_type: MIME.from_path(path)}}
    end
  end

  @doc "Root directory the adapter writes into."
  def root, do: Storage.config(:root) || raise(ArgumentError, "storage :root is not configured")

  # The key is generated by the server, but this module is the last line of
  # defence: a key that would resolve outside the root is refused rather than
  # written, whatever produced it.
  defp absolute_path(key) do
    root = Path.expand(root())
    path = Path.expand(Path.join(root, key))

    cond do
      # `Path.join/2` would quietly graft an absolute key onto the root, which
      # turns "/etc/passwd" into a file that looks stored but is not where the
      # caller thinks. Refuse instead of reinterpreting.
      String.starts_with?(key, "/") -> {:error, :invalid_key}
      String.starts_with?(path, root <> "/") -> {:ok, path}
      true -> {:error, :invalid_key}
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp write(path, {:file, source}) do
    case File.cp(source, path) do
      :ok -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp write(path, data), do: File.write(path, data)

  # sobelow_skip ["Traversal.FileModule"]
  defp read_prefix(path, length) do
    case File.open(path, [:read, :binary]) do
      {:ok, device} ->
        try do
          case IO.binread(device, length) do
            :eof -> {:ok, ""}
            {:error, reason} -> {:error, reason}
            data -> {:ok, data}
          end
        after
          File.close(device)
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp public_prefix, do: Storage.config(:public_prefix, "/uploads")

  defp content_type_header(opts) do
    case Keyword.get(opts, :content_type) do
      nil -> %{}
      content_type -> %{"content-type" => content_type}
    end
  end
end
